export const inventoryFilterableFields: string[] = [
  "product",
  "location",
  "attributes",
  "sku",
  "barcode",
  "attribute_values",
  "regular_price_min",
  "regular_price_max",
  "sale_price_min",
  "sale_price_max",
  "available_quantity_min",
  "available_quantity_max",
  "total_sold_min",
  "total_sold_max",
];
