export enum PRE_ORDER_STATUS {
  INCOMPLETE = "incomplete",
  PENDING = "pending",
  PENDING_APPROVAL = "pending_approval",
  FAILED = "failed",
  PURCHASED = "purchased",
  ON_THE_WAY_TO_BD = "on_the_way_to_bd",
  ARRIVED_BD_WAREHOUSE = "arrived_bd_warehouse",
  INSPECTION_IN_PROGRESS = "inspection_in_progress",
  READY_FOR_DISPATCH = "ready_for_dispatch",
  ACCEPTED = "accepted",
  RTS = "rts",
  HANDED_OVER_TO_COURIER = "handed_over_to_courier",
  IN_TRANSIT = "in_transit",
  DELIVERED = "delivered",
  PENDING_RETURN = "pending_return",
  RETURNED = "returned",
  CANCELLED = "cancelled",
  EXCHANGE_REQUESTED = "exchange_requested",
  EXCHANGED = "exchanged",
  PARTIAL = "partial",
  UNKNOWN = "unknown",
  LOST = "lost",
}
