export const allowedImageTypes = [
  "image/jpeg",
  "image/jpg",
  "image/png",
  "image/webp",
  "image/gif",
  "image/bmp",
  "image/tiff",
  "image/svg+xml",
  "image/x-icon",
  "image/heic",
  "image/heif",
  "image/avif",
  "image/apng",
  "image/x-ms-bmp",
  "image/x-citrix-jpeg",
  "image/x-citrix-png",
];

export const allowedExtensions = [
  ".jpeg",
  ".jpg",
  ".png",
  ".webp",
  ".gif",
  ".bmp",
  ".tiff",
  ".svg",
  ".ico",
  ".heic",
  ".heif",
  ".avif",
  ".apng",
];
